# Generated by Django 4.0 on 2022-01-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='static/img')),
                ('product_description', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=20)),
                ('product_buyer', models.CharField(max_length=20)),
            ],
        ),
    ]
